name: Deploy to Scaleway

on:
  push:
    branches:
      - main

env:
  REGISTRY: rg.fr-par.scw.cloud/myproject

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (pour build multi-plateformes)
        uses: docker/setup-buildx-action@v2

      - name: Login to Scaleway Registry
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.accesKey }}
          password: ${{ secrets.secretKey }}

      - name: Build and push back image
        run: |
          docker build -t $REGISTRY/back:latest ./back
          docker push $REGISTRY/back:latest

      - name: Build and push front image
        run: |
          docker build -t $REGISTRY/front:latest ./front
          docker push $REGISTRY/front:latest
