name: Deploy to Scaleway

on:
  push:
    branches:
      - main

env:
  REGISTRY: rg.fr-par.scw.cloud/namespace-fanny-costesrossignol

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Scaleway Registry
        uses: docker/login-action@v2
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.SCW_REGISTRY_USERNAME }}
          password: ${{ secrets.SCW_REGISTRY_PASSWORD }}

      - name: Build and push back image
        run: |
          docker build -t $REGISTRY/back:latest ./back
          docker push $REGISTRY/back:latest

      - name: Build and push front image
        run: |
          docker build -t $REGISTRY/front:latest ./front
          docker push $REGISTRY/front:latest

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login rg.fr-par.scw.cloud -u ${{ secrets.SCW_REGISTRY_USERNAME }} -p ${{ secrets.SCW_REGISTRY_PASSWORD }}

            docker pull $REGISTRY/back:latest
            docker pull $REGISTRY/front:latest

            docker stop back || true
            docker rm back || true
            docker run -d --name back -p 3000:3000 $REGISTRY/back:latest

            docker stop front || true
            docker rm front || true
            docker run -d --name front -p 80:80 $REGISTRY/front:latest
